name: Deploiement vers ByetHost FTP

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-byethost
  cancel-in-progress: false

jobs:
  web-deploy:
    name: 🎉 Déploiement FTP
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Récupération du code
        uses: actions/checkout@v3

      - name: 📦 Nettoyage du vendor de titiss.space
        # On prépare les dépendances de production AVANT l'envoi
        working-directory: titiss.space/htdocs
        run: composer install --no-dev --optimize-autoloader

      - name: 🗑️ Nettoyage du cache de titiss.space
        # On vide le cache AVANT l'envoi
        working-directory: titiss.space/htdocs
        run: rm -rf writable/cache/*

      - name: 📂 Synchronisation FTP
        # L'envoi FTP se fait en dernier, avec un dossier propre
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          server-dir: /
          state-name: htdocs/.ftp-deploy-sync-state.json
          
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/tests/**
            **/user_guide_src/**
            **/phpunit.xml.dist
            **/.env
            **/spark
            **/README.md
            LICENSE
            composer.json
            composer.lock
            **/vendor/phpunit/**
            **/vendor/fakerphp/**
            **/vendor/symfony/**
            **/vendor/mockery/**
            **/sites_non_lances/
            **/sites_non_lances/**
            **/writable/cache/**
            **/writable/logs/**
            **/writable/session/**